language: node_js
node_js:
  - "node"
# S: Build Lifecycle
install:
  - npm install
  - npm install -S -g hexo-generator-json-content
before_script:
  - npm install -g gulp
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "manyang901"
  - git config user.email "gzmanyang@126.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force "https://${GH_TOKEN}@github.com/manyang901/manyang901.github.io.git" master
# E: Build LifeCycle
branches:
  only:
    - master